config/routes.rb
Rails.application.routes.draw do
  get 'comments/create'

  get 'comments/destroy'

  devise_for :users

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  resources :news
  resources :energies
  resources :houses do
    member do
      get 'EnergyProduction_2011' => 'houses#EnergyProduction_2011'
      get 'EnergyProduction_2012' => 'houses#EnergyProduction_2012'
      get 'EnergyProduction_2013' => 'houses#EnergyProduction_2013'
    end
  end

  root 'events#index'

  resources :articles do
    resources :comments
  end

  resources :events do
    resources :comments
  end

  namespace :customer do
    namespace :webview do
      namespace :external do
        namespace :v1 do
          resources :restaurants, only: %w[show]
        end
      end
    end
  end
#
end

app/models/event.rb
class Event < ApplicationRecord
  has_many :comments, as: :commentable, dependent: :destroy
  belongs_to :user, optional: true, class_name: "User", foreign_key: "users_id"
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  def index
    @events = Event.all
  end

  def show
    @comment = Comment.new
  end

  def new
    #binding.pry
    @event = Event.new
    @user = current_user
  end

  def edit
  end

  def create
    #binding.pry

    @event = Event.new(event_params)
    #@event.users_id = current_user.id   #変更
    # @event.name = params[:event][:neme]
    # @event.content = params[:event][:content]
    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end


  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end


  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to event_index_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  def set_event
    @event = Event.find(params[:id])
    @user = current_user
  end

  def event_params
    #binding.pry

    @user = current_user
    params.require(:event).permit(:name, :content, :users_id).merge(users_id: @user.id)
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= form_with(model: event, local: true) do |form| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :event_name %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content, id: :event_content %>
  </div>



    <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing News</h1>

<%= render 'form', event: @event %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', event_path %>

app/views/events/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Events</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Content</th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event.name %></td>
        <td><%= event.content %></td>
        <td><%= link_to 'Show', event %></td>
        <td><%= link_to 'Edit', edit_event_path(event) %></td>
        <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New event', new_event_path %>

app/views/events/new.html.erb
<h1>New News</h1>

<%= render 'form', event: @event %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @event.name %>
</p>

<p>
  <strong>Content:</strong>
  <%= @event.content %>
</p>


<%= render partial: 'comments/form', locals: { comment: @comment, event: @event } %>

<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', event_path %>